// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
declare module "*.vue" {
  import { ComponentOptions } from "vue";

  const componentOptions: ComponentOptions;
  export default componentOptions;
}
