# Generated by Django 4.0.4 on 2022-07-18 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='菜单名称', max_length=255, null=True)),
                ('path', models.CharField(help_text='菜单组件路径', max_length=255, null=True)),
                ('url', models.CharField(help_text='菜单路由', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False)),
                ('password', models.CharField(help_text='密码', max_length=200)),
                ('tel', models.CharField(help_text='电话号码', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='系统名称', max_length=100)),
                ('menuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vue3_main.menus', verbose_name='外键关联菜单表')),
                ('user', models.ManyToManyField(help_text='关联用户表', to='vue3_main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Tree_Info',
            fields=[
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False)),
                ('ancestorId', models.CharField(help_text='父级和祖父级ID', max_length=255, null=True)),
                ('level', models.CharField(help_text='层级', max_length=255, null=True)),
                ('systemId', models.CharField(help_text='系统id', max_length=11)),
                ('menuId', models.ForeignKey(db_constraint=False, help_text='菜单id', null=True, on_delete=django.db.models.deletion.CASCADE, to='vue3_main.menus')),
            ],
        ),
    ]
