# Generated by Django 4.0.4 on 2022-07-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue3_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False)),
                ('pid', models.CharField(help_text='菜单父级id', max_length=255)),
                ('name', models.CharField(help_text='菜单名称', max_length=255, null=True)),
                ('path', models.CharField(help_text='菜单组件路径', max_length=255, null=True)),
                ('url', models.CharField(help_text='菜单路由', max_length=255, null=True)),
            ],
        ),
    ]
