# Generated by Django 4.0.4 on 2022-07-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vue3_main', '0002_menus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTreeInfo',
            fields=[
                ('id', models.AutoField(help_text='主键id', primary_key=True, serialize=False)),
                ('menuId', models.CharField(help_text='菜单id', max_length=255, null=True)),
                ('ancestorId', models.CharField(help_text='父级和祖父级ID', max_length=255, null=True)),
                ('level', models.CharField(help_text='层级', max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menus',
            name='pid',
        ),
    ]
