# Generated by Django 4.0.4 on 2022-07-12 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vue3_main', '0004_menu_tree_info_delete_menutreeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_tree_info',
            name='menuId',
            field=models.ForeignKey(help_text='菜单id', null=True, on_delete=django.db.models.deletion.CASCADE, to='vue3_main.menus'),
        ),
    ]
