# Generated by Django 4.0.4 on 2022-06-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
