# Generated by Django 4.0.4 on 2022-06-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
