HOSTNAME = '112.124.37.144'
PORT = "3306"
DATABASE = 'Blob'
USERNAME = 'root'
PASSWORD = 'L_jj1998'
DB_URL = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(
    USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE)

SQLALCHEMY_DATABASE_URI = DB_URL
SQLALCHEMY_TRACK_MODIFICATIONS = True
